import type { Language } from '@/hooks/usePreferences';

const SAMPLES_EN = [
  'Dreamy lo-fi hip hop at 78 bpm in F# minor: dusty boom-bap kick on 1 and 3, soft snare with vinyl crackle on 2 and 4, swung closed hats, warm Rhodes 7th chords (F#m9 - Bmaj7 - C#m7 - A6) with light low-pass filter, a sub bass following the chord roots, and gentle tape hiss plus long room reverb for a late-night studying mood.',
  'Driving 130 bpm techno in A minor: relentless 4-on-the-floor kick, off-beat open hats and clap on 2/4, a hypnotic 16th-note acid bassline (a1 a2 c2 e2 g1 a2 c3 e2) on a sawtooth synth with slowly opening resonant low-pass filter, sparse industrial percussion stabs, layered with a moody dark pad in the background and heavy plate reverb on the snare.',
  'Spacious ambient soundscape in C minor at 60 bpm: slow evolving pad chords (Cm9 - Abmaj7 - Ebmaj7 - Gm7) with long attack and release, glassy bell arpeggios drifting in the high register, sub-bass drone holding the tonic, ocean-like noise sweeps panning gently left and right, generous hall reverb and long delay, evoking a calm starlit night.',
  'Smooth late-night jazz trio at 95 bpm in Bb major: upright walking bass outlining ii-V-I changes (Cm7 - F7 - Bbmaj7 - G7), brushed snare swing pattern with soft ride cymbal on the bell, mellow Rhodes piano comping syncopated 9th and 13th voicings, a tasteful muted trumpet improvising a short bluesy phrase every 4 bars, light room reverb and warm tape saturation.',
];

const SAMPLES_ZH = [
  '梦幻 lo-fi hip hop，78 bpm，升 F 小调：1、3 拍上是带灰尘感的 boom-bap 底鼓，2、4 拍是柔和军鼓配黑胶噪声，摇摆律动的闭镲，温暖的 Rhodes 七和弦（F#m9 - Bmaj7 - C#m7 - A6）经过轻微低通滤波，sub 贝斯跟随根音走动，叠加磁带嘶声和较长的房间混响，营造深夜自习的慵懒氛围。',
  '推进感强烈的 techno，130 bpm，A 小调：稳定的四四拍底鼓，反拍开镲与 2/4 拍 clap，催眠般的 16 分酸性贝斯线（a1 a2 c2 e2 g1 a2 c3 e2）使用锯齿波合成器，配缓慢打开的共振低通滤波，零星的工业感打击 stab，底层叠加阴郁的暗色 pad，军鼓加重 plate 混响。',
  '辽阔的氛围音景，C 小调，60 bpm：缓慢演进的 pad 和弦（Cm9 - Abmaj7 - Ebmaj7 - Gm7），attack 与 release 都很长；高音区有玻璃般的钟琴琶音飘过，sub 贝斯持续低吟主音；海浪般的噪声 sweep 左右轻轻摇移，大厅混响与长延迟充足，仿佛宁静的星空夜晚。',
  '深夜爵士三重奏，95 bpm，降 B 大调：贝斯以行走低音勾勒 ii-V-I 进行（Cm7 - F7 - Bbmaj7 - G7），刷扫军鼓配吊镲铃部摇摆律动，温润的 Rhodes 钢琴使用切分的 9 和 13 音色伴奏，每 4 小节加入一段含蓄的弱音小号布鲁斯短乐句，轻微房间混响与磁带饱和。',
];

export const STRINGS = {
  en: {
    appTagline: 'LLM → Strudel → Audio',
    settings: 'Settings',
    usingDefault: 'Using built-in default endpoint',
    todayQuota: (used: number, limit: number) => `today ${used}/${limit}`,
    customEndpointsCount: (n: number) => `${n} custom endpoint${n === 1 ? '' : 's'}`,

    promptLabel: 'Describe your music',
    promptPlaceholder: 'e.g. lo-fi hip hop with mellow piano chord',
    samples: SAMPLES_EN,
    generate: 'Generate',
    generating: 'Generating…',

    willUseDefault:
      'No custom endpoint configured. The built-in default endpoint will be used (100 daily requests shared across all users).',
    willUseCustom: (n: number) =>
      `Will call ${n} custom endpoint${n === 1 ? '' : 's'} concurrently and show one result per endpoint.`,

    quotaHint: '→ Add your own AI endpoint in ⚙ Settings to keep going.',

    history: 'History',
    historyLoading: 'loading…',
    historyEmpty: 'No tracks yet. Generate one!',
    deleteAria: 'Delete',

    sourceDefault: 'This run was generated by the built-in default endpoint.',
    sourceUser: (n: number) =>
      `This run was generated concurrently by ${n} custom endpoint${n === 1 ? '' : 's'} (one music result per endpoint).`,
    singletonNote:
      'Note: the Strudel engine is a global singleton — only one panel can play at a time.',

    emptyTitleDefault: 'Type the music style you want on the left, then click Generate.',
    emptyTitleCustom: (n: number) =>
      `${n} endpoint${n === 1 ? '' : 's'} configured. Click Generate to call them concurrently and view each result below.`,
    emptyHint:
      'Want to use your own endpoint? Open ⚙ Settings (top right) to add Name / Base URL / API Key / Model.',

    panelHideRaw: 'hide raw',
    panelShowRaw: 'show raw',
    panelUnknownError: 'Unknown error',

    playerReady: 'Ready',
    playerLoading: 'Loading samples…',
    playerEngineReady: 'Engine ready',
    playerPlaying: 'Playing',
    playerError: 'Error',
    playerPlay: '▶ Play',
    playerStop: '■ Stop',
    playerHint:
      'First Play loads dirt-samples (~MBs from GitHub). Audio requires a user click — browser autoplay policy.',
    playerErrorTitle: 'Code error — please regenerate or fix manually:',
    codePlaceholder: '// Strudel code will appear here',

    drawerClose: 'Close',
    drawerTitle: 'Settings',

    sectionLanguage: 'Language',
    languageHint:
      'Affects the Prompt textarea label, placeholder, sample prompts, and other UI copy.',

    sectionAppearance: 'Appearance',
    themeLabel: 'Theme',
    themeSystem: 'System',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeHint: 'Defaults to system — automatically follows your OS light/dark setting.',

    sectionEndpoints: 'AI endpoint settings',
    endpointsIntro1:
      'Endpoints are saved in your browser localStorage only and forwarded to this server on every generation.',
    endpointsIntro2:
      'If any endpoint is configured, the built-in default endpoint is no longer used; you get one music result per endpoint.',
    endpointsIntro3:
      'The Test button next to each endpoint runs the cheapest possible request to verify connectivity.',
    endpointEmpty:
      'No custom endpoint yet. Click "+ Add endpoint" below to add one. Otherwise the built-in default endpoint (max 100/day) will be used.',
    endpointIndex: (i: number) => `Endpoint #${i}`,
    fieldName: 'Name',
    fieldNamePlaceholder: 'e.g. My OpenAI / DeepSeek main / OpenRouter Claude',
    fieldBaseURL: 'Base URL',
    fieldAPIKey: 'API Key',
    fieldModel: 'Model',
    deleteEndpoint: 'Delete endpoint',
    test: 'Test',
    testing: 'Testing…',
    testPassed: 'passed',
    addEndpoint: '+ Add endpoint',
    save: 'Save',
    cancel: 'Cancel',
    clearAll: 'Clear all',
    clearConfirm: 'Clear all endpoints? Will fall back to the built-in default endpoint.',
    fillFirst: 'Please fill in Base URL / API Key / Model first.',
    testReply: 'reply',
  },
  zh: {
    appTagline: 'LLM → Strudel → 音频',
    settings: '设置',
    usingDefault: '使用官方默认接口',
    todayQuota: (used: number, limit: number) => `今日 ${used}/${limit}`,
    customEndpointsCount: (n: number) => `${n} 个自定义接口`,

    promptLabel: '描述你想要的音乐',
    promptPlaceholder: '例如：低保真 hip hop，搭配柔和的钢琴和弦',
    samples: SAMPLES_ZH,
    generate: '生成',
    generating: '生成中…',

    willUseDefault: '尚未配置自定义接口，将调用官方默认接口（每日 100 次共享额度）。',
    willUseCustom: (n: number) => `将同时调用 ${n} 个自定义接口并分别生成。`,

    quotaHint: '→ 在 ⚙ 设置中添加你的 AI 接口即可继续使用。',

    history: '历史记录',
    historyLoading: '加载中…',
    historyEmpty: '还没有任何作品，快去生成一个吧！',
    deleteAria: '删除',

    sourceDefault: '本次由官方默认接口生成。',
    sourceUser: (n: number) => `本次由 ${n} 个自定义接口并发生成（每个接口对应一个音乐结果）。`,
    singletonNote: '注意：Strudel 引擎是全局单例，同一时间只能播放一个面板。',

    emptyTitleDefault: '在左侧输入想要的音乐风格，然后点击「生成」。',
    emptyTitleCustom: (n: number) =>
      `已配置 ${n} 个接口，点击「生成」后将并发调用，并分别展示生成结果。`,
    emptyHint: '想用自己的接口？打开右上角 ⚙ 设置，添加 名称 / Base URL / API Key / Model。',

    panelHideRaw: '隐藏原始输出',
    panelShowRaw: '查看原始输出',
    panelUnknownError: '未知错误',

    playerReady: '就绪',
    playerLoading: '正在加载采样…',
    playerEngineReady: '引擎已就绪',
    playerPlaying: '播放中',
    playerError: '错误',
    playerPlay: '▶ 播放',
    playerStop: '■ 停止',
    playerHint: '首次播放会从 GitHub 加载 dirt-samples（数 MB）。受浏览器自动播放策略限制，必须由用户点击触发。',
    playerErrorTitle: '代码运行出错——请尝试重新生成或手动修改：',
    codePlaceholder: '// 生成的 Strudel 代码会显示在这里',

    drawerClose: '关闭',
    drawerTitle: '设置',

    sectionLanguage: '语言 / Language',
    languageHint: '影响 Prompt 输入框的标签、占位符、示例 prompt 以及其他界面文案。',

    sectionAppearance: '外观',
    themeLabel: '主题',
    themeSystem: '跟随系统',
    themeLight: '白天',
    themeDark: '暗黑',
    themeHint: '默认跟随系统设置自动切换深浅色。',

    sectionEndpoints: 'AI 接口设置',
    endpointsIntro1:
      '这里配置的接口仅保存在浏览器 localStorage 中，每次生成时随请求转发到本服务器。',
    endpointsIntro2:
      '只要你配置了任意一个接口，就不会再调用官方默认接口；有几个接口就会同时生成几个音乐。',
    endpointsIntro3: '每个接口旁边的 Test 按钮可以用最低成本验证接口是否能跑通。',
    endpointEmpty: '还没有自定义接口。点击下方「+ 新增接口」来添加。未添加时将使用官方默认接口（每天最多 100 次）。',
    endpointIndex: (i: number) => `接口 #${i}`,
    fieldName: '名称',
    fieldNamePlaceholder: '例如：My OpenAI / DeepSeek 主号 / OpenRouter Claude',
    fieldBaseURL: 'Base URL',
    fieldAPIKey: 'API Key',
    fieldModel: 'Model',
    deleteEndpoint: '删除接口',
    test: 'Test',
    testing: 'Testing…',
    testPassed: '通过',
    addEndpoint: '＋ 新增接口',
    save: '保存',
    cancel: '取消',
    clearAll: '全部清空',
    clearConfirm: '清空所有接口？将回退到使用官方默认接口。',
    fillFirst: '请先填完整 Base URL / API Key / Model。',
    testReply: '回应',
  },
};

export type Strings = (typeof STRINGS)['en'];

export function getStrings(lang: Language): Strings {
  return STRINGS[lang] as Strings;
}
